# Enable debug info in console
debug-mode: true

# Enable colors in console output
color-logs: true

# Enable misc logging alerts in console output
logging: true

# Language file (for translations)
language-file: lang-en.yml

# Enables/Disabled Treee Spawner Tool
treee-spawner-tool-click: true